[versions]
androidx-junit = "1.1.4"
# TODO Next two versions must be > 1.6.0
appcompat = "1.6.1"
androidx-activity="1.7.2"
constraintlayout = "2.1.4"
core-ktx = "1.7.0"
epoxyVer = "5.1.1"
espresso-core = "3.5.0"
junit = "4.13.2"
material = "1.7.0"
navigation-ui-ktx = "2.5.3"
navigation = "2.5.3"
navigation-fragment-ktx = "2.5.3"
android-application = "8.1.0"
kotlin = "1.8.10"
google-shortcuts = "1.0.0"
viewpager = "1.0.0"
koin_version = "3.5.3"
room-runtime = "2.5.2"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-activity= { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-ui-ktx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
epoxy = { module = "com.airbnb.android:epoxy", version.ref = "epoxyVer" }
epoxy-databinding = { module = "com.airbnb.android:epoxy-databinding", version.ref = "epoxyVer" }
epoxy-processor = { module = "com.airbnb.android:epoxy-processor", version.ref = "epoxyVer" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
google-shortcuts = { module = "androidx.core:core-google-shortcuts", version.ref = "google-shortcuts" }
viewpager = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager" }
koin = { module = "io.insert-koin:koin-android", version.ref = "koin_version" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-runtime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-runtime" }

[plugins]

android-application = { id = "com.android.application", version.ref="android-application" }
android-library = { id = "com.android.library", version.ref="android-application" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref="kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
safe-args = { id = "androidx.navigation.safeargs", version.ref = "navigation" }

[bundles]

