name: Build and Test app module

on:
  push:
    branches:
      - main
    paths:
      - app/**

  workflow_dispatch:


jobs:
  java_version:
    name: Use Java
    runs-on: ubuntu-latest

    steps:
      - name: Print Java
        run: javac -version