name: Build and Test app module

on:
  push:
    branches:
      - main
    paths:
      - app/**

  workflow_dispatch:


jobs:
  java_version:
    name: Use Java
    runs-on: ubuntu-latest
    #    Runs only when commit message startsWith 'Update'
    #    if: startsWith(github.event.head_commit.message, 'Update')
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

        # Print Hello, world!
      - name: Run a one-line script
        run: echo Hello, world!

      # Print Java compiler version
      - name: Print Java
        run: javac -version

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run Debug Tests
        run: ./gradlew testDebugUnitTest