name: Build and Test app module

on:
  push:
    branches:
      - main
    paths:
      - app/**

  workflow_dispatch:


jobs:
  java_version:
    name: Use Java
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Update')

    steps:
      - uses: actions/checkout@v4
        # Print Hello, world!
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Print Java
        run: javac -version